# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181017_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
                'ordering': ['student'],
            },
        ),
    ]
