# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Назва предмету')),
                ('teacher_first_name', models.CharField(max_length=256, verbose_name="Ім'я")),
                ('teacher_last_name', models.CharField(max_length=256, verbose_name='Прізвище')),
                ('teacher_middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='По-батькові')),
                ('data', models.DateField(null=True, verbose_name='Дата іспиту')),
                ('exam_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Іспит',
                'verbose_name_plural': 'Іспити',
                'ordering': ['subject'],
            },
        ),
        migrations.RemoveField(
            model_name='journal',
            name='student',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
