# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181107_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
    ]
