# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20181109_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='data',
            new_name='date',
        ),
    ]
