# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-31 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190123_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=256, null=True, verbose_name='Оцінка')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Студент')),
                ('subject_exam', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Результат Іспиту',
                'verbose_name_plural': 'Результати Іспитів',
            },
        ),
    ]
