# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_examresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Місячний Журнал',
                'verbose_name_plural': 'Місячні Журнали',
            },
        ),
    ]
