# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20190620_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Date exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Date exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_uk',
            field=models.DateField(null=True, verbose_name='Date exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Title subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Title subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Title subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_first_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_last_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_middle_name_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_middle_name_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_middle_name_uk',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='date_uk',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='student_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='student_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='monthjournal',
            name='student_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', unique_for_month='date', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_en',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_ru',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name_uk',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
    ]
