# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20190622_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.PositiveIntegerField(unique=True, verbose_name='Ticket'),
        ),
    ]
