# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20190820_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to=students.models.upload_to, verbose_name='File')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'This type already exist'}, max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'The type of Document',
                'verbose_name_plural': 'Types of Documents',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Type', verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('student', 'type')]),
        ),
    ]
