# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20191014_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='files/', validators=[students.validators.validate_file_extension], verbose_name='File'),
        ),
    ]
