# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=13, verbose_name='Mobile Phone')),
                ('passport', models.CharField(blank=True, max_length=8, verbose_name='Passport number')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=25, verbose_name='Street')),
                ('house', models.CharField(blank=True, max_length=5, verbose_name='House')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
