# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stprofile',
            options={'verbose_name': 'Профіль Користувача'},
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='house',
            field=models.CharField(blank=True, max_length=5, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=8, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='street',
            field=models.CharField(blank=True, max_length=25, verbose_name='Вулиця'),
        ),
    ]
