# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='house',
            field=models.CharField(blank=True, max_length=5, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=8, verbose_name='Passport number'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='street',
            field=models.CharField(blank=True, max_length=25, verbose_name='Street'),
        ),
    ]
