# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import stud_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0002_auto_20190809_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=stud_auth.models.upload_to, verbose_name='Фото'),
        ),
    ]
