# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0002_auto_20190704_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='city_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='city_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='city_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='house_en',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='house_ru',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='house_uk',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='House'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='mobile_phone_en',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='mobile_phone_ru',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='mobile_phone_uk',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport_en',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Passport number'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport_ru',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Passport number'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport_uk',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Passport number'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo_en',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo_ru',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo_uk',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='street_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='street_ru',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='street_uk',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Street'),
        ),
    ]
