# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_auth', '0003_auto_20190704_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stprofile',
            options={'verbose_name': 'Профіль Користувача'},
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='city_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='city_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='city_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='house',
            field=models.CharField(blank=True, max_length=5, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='house_en',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='house_ru',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='house_uk',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone_en',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone_ru',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone_uk',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=8, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport_en',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport_ru',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport_uk',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='street',
            field=models.CharField(blank=True, max_length=25, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='street_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='street_ru',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='street_uk',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Вулиця'),
        ),
    ]
